In [1]:
import pandas as pd

df = pd.read_csv('lpor_explorer.csv')

# One-hot encode columns in columns with 2 categories
df = pd.get_dummies(df, columns=['Escola', 'Sexo', 'TP_Moradia', 'Tamanho_Familia', 'Situacao_Pais', 'Apoio_Educacao_Extra', 'Apoio_Educacao_Pais', 'Aulas_Particulares', 'Tem_Internet', 'Quer_Fazer_Graduacao', 'Frequentou_Creche', 'Ativ_Extracurricular', 'Esta_Namorando'])
# One-hot encode columns in columns with more than 2 categories
df = pd.get_dummies(df, columns=['Motivo_Escolha_Escolar', 'Responsavel_Legal'])
# Drop columns: 'Frequentou_Creche_Não', 'Escola_Mousinho da Silveira' and 11 other columns
df = df.drop(columns=['Responsavel_Legal_Outro', 'Motivo_Escolha_Escolar_Outro', 'Frequentou_Creche_Não', 'Escola_Mousinho da Silveira', 'Sexo_Mulher', 'TP_Moradia_Rural', 'Tamanho_Familia_Até 3', 'Situacao_Pais_Morando Juntos', 'Apoio_Educacao_Extra_Não', 'Apoio_Educacao_Pais_Não', 'Aulas_Particulares_Não', 'Tem_Internet_Não', 'Quer_Fazer_Graduacao_Não', 'Ativ_Extracurricular_Não', 'Esta_Namorando_Não'])
df.columns = df.columns.str.replace('_Sim', '')    

# Put numbers instead categories in a column
def encoding(column, categories):
    for i, category in enumerate(categories):
        column = column.replace(category, i)
    df[column.name] = column

encoding(df.Estado_Saude, ['Muito Ruim', 'Ruim', 'Razoavel', 'Bom', 'Muito Bom'])
encoding(df.Boa_Convivencia_Familia, ['Muito Ruim', 'Ruim', 'Razoavel', 'Bom', 'Excelente'])
encoding(df.Tempo_Estudo_Semanal, ['Até 2h,', '2 a 5h', '5 a 10h', 'Mais de 10h'])
encoding(df.Tempo_ida_Escola, ['Até 15 min', '15 a 30 min', '30 min a 1h', 'Mais de 1h'])
encoding(df.Educacao_Pai, ['Nenhuma', 'Ensino Fundamental 1', 'Ensino Fundamental 2', 'Ensino Médio', 'Ensino Superior'])
encoding(df.Educacao_Mae, ['Nenhuma', 'Ensino Fundamental 1', 'Ensino Fundamental 2', 'Ensino Médio', 'Ensino Superior'])
cat = ['Muito Baixo', 'Baixo', 'Moderado', 'Alto', 'Muito Alto']
encoding(df.Tempo_Livre_Apos_Escola, cat)
encoding(df.Tempo_com_Amigos, cat)
encoding(df.Alcool_Dia_Util, cat)
encoding(df.Alcool_Fim_Semana, cat)

df

#trabalho mae
#trabalho pai

,idade,Educacao_Mae,Educacao_Pai,Trabalho_Mae,Trabalho_Pai,Tempo_ida_Escola,Tempo_Estudo_Semanal,Boa_Convivencia_Familia,Tempo_Livre_Apos_Escola,Tempo_com_Amigos,...,Tem_Internet,Quer_Fazer_Graduacao,Frequentou_Creche,Ativ_Extracurricular,Esta_Namorando,Motivo_Escolha_Escolar_Perto de Casa,Motivo_Escolha_Escolar_Preferência pelo Curso,Motivo_Escolha_Escolar_Reputação,Responsavel_Legal_Mãe,Responsavel_Legal_Pai
0,18,4,4,Do Lar,Professor,1,1,3,2,3,...,False,True,True,False,False,False,True,False,True,False
1,17,1,1,Do Lar,other,0,1,4,2,2,...,True,True,False,False,False,False,True,False,False,True
2,15,1,1,Do Lar,other,0,1,3,2,1,...,True,True,True,False,False,False,False,False,True,False
3,15,4,2,Saúde,Serviços,0,2,2,1,1,...,True,True,True,True,True,True,False,False,True,False
4,16,3,3,other,other,0,1,3,2,1,...,False,True,True,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644,19,2,3,Serviços,other,0,2,4,3,1,...,True,True,False,True,False,False,True,False,True,False
645,18,3,1,Professor,Serviços,0,1,3,2,3,...,True,True,True,False,False,False,True,False,True,False
646,18,1,1,other,other,1,1,0,0,0,...,False,True,True,True,False,False,True,False,True,False
647,17,3,1,Serviços,Serviços,1,0,1,3,4,...,True,True,False,False,False,False,True,False,True,False
648,18,3,2,Serviços,other,2,0,3,3,0,...,True,True,False,False,False,False,True,False,True,False